Feature/task 0 refactor news module with the new architecture
nastkaval/NewsApp pull request #21
Opened 2020-10-28 08:47 UTC by nastkaval

#20

2020-10-28 09:10 UTC, vitali-kazakevich requested changes

2020-10-28 09:10 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/View/NewsView.swift
> +  var delegate: NewsControllable?
называй по сути. 
это контроллер у вьюхи

2020-10-28 09:10 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/View/NewsView.swift
> +  private var dataSource: [NewsViewModel]?
private var viewModels: [NewsViewModel] = []

2020-10-28 09:10 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/View/NewsView.swift
> +  func didSwipeRefresh()
func didLoadView()
  func didTapMenu()
  func didTapOffline()
  func didTapDetails(at index: IndexPath)
  func didStartFilter(keyWord: String)
  func didScroll()
  func didRefresh()
}

2020-10-28 09:10 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Model/NewsModel.swift
> +  func filteringData(by keyWord: String) -> [News] {
-ing здесь не подходит 
а ты расскажи мне почему:)

2020-10-28 09:10 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Model/NewsModel.swift
> +  var dataSource: [News] {
items будет понятнее

2020-10-28 09:10 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Model/NewsModel.swift
> +  var dataSource: [News] { get }
items будет понятнее

2020-10-28 09:10 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Coordinator/NewsViewCoordinator.swift
> +    let controller = NewsController(model: model, delegate: view, newsModuleOutput: self)
думаю поле лучше назвать output. и так понятно что это за аутпут.
стремимся к простоте

2020-10-28 09:28 UTC, nastkaval commented on NewsApp/Scenes/NewsScene/Controller/NewsController.swift
> +  var imageUrl: URL? { get }
Чтобы картинку по этому юрлу загрузить и отобразить через alamofire image

2020-10-28 09:47 UTC, nastkaval commented on NewsApp/Scenes/NewsScene/Model/NewsModel.swift
> +  func filteringData(by keyWord: String) -> [News] {
Не знаю почему, название - глагол с ing окончанием, отражает работу функции - фильтрация данных по ключу. Или ты о том, что так как функа отдает что-то, то надо называть через make? И будет makeDataFiltered(with keyWord: )?

2020-10-28 10:01 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Model/NewsModel.swift
> +  func filteringData(by keyWord: String) -> [News] {
https://swift.org/documentation/api-design-guidelines/

2020-10-28 10:38 UTC, nastkaval commented on NewsApp/Scenes/NewsScene/Model/NewsModel.swift
> +  func filteringData(by keyWord: String) -> [News] {
`Those with side-effects should read as imperative verb phrases`
Значит func filterData

2020-10-28 10:51 UTC, nastkaval commented on NewsApp/Scenes/NewsScene/Model/NewsModel.swift
> +  func filteringData(by keyWord: String) -> [News] {
`When the operation is naturally described by a verb, use the verb’s imperative for the mutating method and apply the “ed” or “ing” suffix to name its nonmutating counterpart.`

`Prefer to name the nonmutating variant using the verb’s past participle (usually appending “ed”)`

`When adding “ed” is not grammatical because the verb has a direct object, name the nonmutating variant using the verb’s present participle, by appending “ing.”`

Разве правильнее будет добавить "ed"? Так как слово filter в названии функции "has a direct object" в виде "data". И понятие filteredData означает "отфильтрованные данные". Тогда надо назвать просто filtered, ты об этом?

2020-10-28 12:49 UTC, vitali-kazakevich requested changes

2020-10-28 12:49 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Controller/NewsController.swift
> +  var descriptionNews: String { get }
когда именуешь что-то внутри объекта, не нужно дублировать:
newsViewModel.isNewsSaved -> newsViewModel.isSaved
newsViewModel.descriptionNews -> newsViewModel.description

2020-10-28 12:49 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Controller/NewsController.swift
> +protocol NewsViewable: AnyObject {
давай все протоколы вынесем в отдельный файл, чтобы проще было составлять общее понимание модуля.
например NewsContract.swift
или NewsProtocols.Swift

и так для каждого модуля будет.

2020-10-28 12:49 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Controller/NewsController.swift
> +protocol NewsModuleOutput: AnyObject {
NewsOutput будет достаточно.

2020-10-28 12:49 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Controller/NewsController.swift
> +  func openDetailsNews(news: News)
openDetails(for news: News)
openSavedNews

что думаешь?

2020-10-28 12:49 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Controller/NewsController.swift
> +  private let newsModuleOutput: NewsModuleOutput
output достаточно

2020-10-28 12:49 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Controller/NewsController.swift
> +    self.newsModuleOutput = output
если в таком виде, то селф не нужен

2020-10-28 12:49 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Controller/NewsController.swift
> +    model.loadDataFromApi(withNextPage: false)
loadData достаточно тут, как я вижу

2020-10-28 12:49 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Controller/NewsController.swift
> +    model.loadDataFromApi(withNextPage: false)
имя bool параметра не звучит как утверждение

2020-10-28 12:49 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Controller/NewsController.swift
> -    isFiltering = false
а это поле вообще нужно теперь? если нет то удали

2020-10-28 12:49 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Controller/NewsController.swift
> +    return urlToImage
а есть смысл ли в таких именах.. мне кажется проще назвать одинаково и не писать дополнительных проперти..

2020-10-28 12:49 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Controller/NewsController.swift
> +    return publishedAtDate
тоже самое, может назвать одинаково?

2020-10-28 12:49 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Model/NewsModel.swift
> +  private var newsArray: [News] = []
тоже самое, давай назовем items

2020-10-28 12:49 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Model/NewsModel.swift
> +    guard !keyWord.isEmpty, keyWord.count > 2 else {
вот задался тут вопросом..

isEmpty ~ count == 0
count == 0 это частный случай count <= 2.

2020-10-28 12:49 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/View/NewsView.swift
> +      controller?.didScroll()
думаю в таком случае корректнее будет didScrollToEnd

2020-10-28 12:54 UTC, nastkaval commented on NewsApp/Scenes/NewsScene/Controller/NewsController.swift
> +  func openDetailsNews(news: News)
openDetails(for news: News) - идеально.

И ты имеешь в виду переименовать func openOfflineCollectionNews() в func openSavedNews()? Я просто называла функи по имени модуля. Тогда модуль OfflineNewsCollection надо будет переименовать в SavedNews или просто в OfflineNews, и тогда функа будет openOfflineNews()

2020-10-29 08:27 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Controller/NewsController.swift
> +  func openDetailsNews(news: News)
ну да, для этого модуля какое-то слишком странное название.. так что его бы тоже переименовать

2020-10-29 09:51 UTC, vitali-kazakevich requested changes

2020-10-29 09:51 UTC, vitali-kazakevich commented on NewsApp/Scenes/DetailesScene/Controller/DetailsController.swift
> +    let newsUrl = object.urlNews
это шутка такая?)

2020-10-29 09:51 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Controller/NewsController.swift
> +extension News: NewsViewModel {
верни скобочку на место

2020-10-29 09:51 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Model/NewsModel.swift
> +    guard keyWord.count > 2 else {
копипаста логики

2020-10-29 09:51 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/NewsProtocols.swift
> +  func openOfflineCollectionNews()
вроде же договорились переименовать

2020-10-29 11:29 UTC, nastkaval commented on NewsApp/Scenes/NewsScene/NewsProtocols.swift
> +  func openOfflineCollectionNews()
мы не пришли к консенсусу, вопрос: называть модуль сохраненных новостей с технической точки зрения - SavedNews, или с бизнесовой - OfflineNews. Потому что ведь есть такое понятие, как работа приложения в оффлайне

2020-10-29 11:43 UTC, nastkaval commented on NewsApp/Scenes/DetailesScene/Controller/DetailsController.swift
> +    let newsUrl = object.urlNews
да вроде нет, я убрала разночтение между клиентской и доменной моделью. клиентская модель теперь содержит переменные, которые называются также, как и в доменной. или, возможно, я не так поняла твой коммент?

2020-10-29 14:12 UTC, vitali-kazakevich requested changes

2020-10-29 14:12 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Model/NewsModel.swift
> +  var isFiltering: Bool = false
private(set)

2020-10-29 14:12 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Model/NewsModel.swift
> +    guard keyWord.count > 2 else {
зачем два гуарда?

2020-10-29 14:12 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Model/NewsModel.swift
> +    let filteredArray = items.filter { $0.title.lowercased().contains("\(keyWord.lowercased())") }
а че бы сразу не вернуть?

2020-10-30 04:52 UTC, vitali-kazakevich requested changes

2020-10-30 04:52 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/Controller/NewsController.swift
> +    if !model.isFiltering {
тут  guard больше подходит по смыслу

2020-10-30 04:52 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/NewsProtocols.swift
> +  var descriptionNews: String { get }
description

2020-10-30 04:52 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/View/NewsView.swift
> +    controller?.didStartFilter(keyWord: sender.text ?? "")
опа.)
ну раз так, то убери ка опшнл из протокола модели))

2020-10-30 04:52 UTC, vitali-kazakevich commented on NewsApp/Scenes/NewsScene/NewsProtocols.swift
> +  func didTapDetails(at index: IndexPath)
тут параметром достаточно инта будет.

2020-10-30 10:42 UTC, vitali-kazakevich approved these changes

2020-10-30 12:37 UTC, merged